# @SI_Copyright@
# @SI_Copyright@

ROLLROOT	= ../..
PKGROOT		= /etc/docker/demos

include $(STACKBUILD)/etc/CCRules.mk

build:

install::	
	mkdir -p $(ROOT)$(PKGROOT)
	$(INSTALL) -m0644 *.sh $(ROOT)$(PKGROOT)
