# @SI_Copyright@
# @SI_Copyright@

PKGROOT		= /export/stack/spreadsheets/examples
ROLLROOT	= ../..

include $(STACKBUILD)/etc/CCRules.mk

build::

install::
	mkdir -p $(ROOT)$(PKGROOT)
	cp *.csv $(ROOT)$(PKGROOT)
